apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tools-dashboard.fullname" . }}-rolebinding
  labels:
    {{- include "tools-dashboard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tools-dashboard.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "tools-dashboard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
